Added a module for converting to/from dicts
EMMC-ASBL/tripper pull request #126
Opened 2023-08-24 17:44 UTC by jesper-friis

# Description:
Added a module for converting to/from dicts

## Type of change:

- [ ] Bug fix.
- [x] New feature.
- [ ] Documentation update.
- [ ] Testing.

## Checklist for the reviewer:

This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

2023-08-25 07:17 UTC, Treesarj approved these changes

2023-08-25 07:18 UTC, Treesarj reviewed
Looks good but build is failing(pls fix)

2023-08-28 11:13 UTC, CasperWA requested changes
this might fix the docs build issue?

2023-08-28 11:13 UTC, CasperWA commented on tripper/convert/convert.py
> +        lang: Language to use for keys.
```suggestion
```
Also, add documentation for `ts` parameter.

2023-08-28 13:55 UTC, CasperWA commented on tripper/convert/convert.py
> +        lang: Language to use for keys.
Conclusion: It needed to be added to the function signature.

2023-08-28 13:55 UTC, CasperWA approved these changes

2023-08-28 14:25 UTC, merged