Added csv parser to Tabledoc (using the built-in csv module)
EMMC-ASBL/tripper pull request #275
Opened 2024-12-19 09:56 UTC by jesper-friis

# Description

## Type of change
- [ ] Bug fix and code cleanup
- [ ] New feature
- [ ] Documentation update
- [ ] Testing

## Checklist for the reviewer
This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?
- [ ] Is the code properly tested?

2024-12-19 14:00 UTC, torhaugl approved these changes

2024-12-19 14:09 UTC, torhaugl requested changes
Verify that test works

2024-12-19 14:09 UTC, torhaugl commented on tests/dataset/test_tabledoc.py
> +    """Test parsing a csv file."""
The output of this tests seems wrong?

```
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix emmo: <https://w3id.org/emmo#> .

<https://he-matchmaker.eu/data/sem/SEM_cement_batch2> a dcat:Dataset,
        emmo:EMMO_194e367c_9783_4bf5_96d0_9ad597d48d9a .

<https://he-matchmaker.eu/data/sem/SEM_cement_batch2/77600-23-001> a dcat:Dataset,
        emmo:EMMO_194e367c_9783_4bf5_96d0_9ad597d48d9a .

<https://he-matchmaker.eu/data/sem/SEM_cement_batch2/77600-23-001/77600-23-001_5kV_400x_m001> a dcat:Dataset,
        emmo:EMMO_194e367c_9783_4bf5_96d0_9ad597d48d9a .

<https://he-matchmaker.eu/sample/SEM_cement_batch2/77600-23-001> a dcat:Dataset,
        emmo:EMMO_194e367c_9783_4bf5_96d0_9ad597d48d9a .
 ```

2024-12-30 14:45 UTC, jesper-friis commented on tests/dataset/test_tabledoc.py
> +    """Test parsing a csv file."""
> The output of this tests seems wrong? 

This is now corrected

2025-01-03 22:34 UTC, merged