Updated import statements in the tutorial
EMMC-ASBL/tripper pull request #40
Opened 2022-11-21 17:45 UTC by jesper-friis

Simple PR correcting the tutorial.

Maybe we could consider to make a test that run doctest on it to ensure that it actually works.

2022-11-22 08:05 UTC, CasperWA approved these changes
Does `doctest` run the Python code? What is `doctest`?

2022-11-22 08:06 UTC, CasperWA requested changes

2022-11-22 08:06 UTC, CasperWA commented on docs/tutorial.md
>  # It is equivalent to ``triplestore.Literal(msg, lang="en")``.
```suggestion
# It is equivalent to ``tripper.triplestore.Literal(msg, lang="en")``.
```

2022-11-22 22:06 UTC, jesper-friis commented
> Does `doctest` run the Python code? What is `doctest`?

[doctest](https://docs.python.org/3/library/doctest.html) runs Python code in docstrings. Good for ensuring that the documentation is up-to-date and that examples actually works.

2022-11-23 10:33 UTC, CasperWA commented
> > Does `doctest` run the Python code? What is `doctest`?
> 
> [doctest](https://docs.python.org/3/library/doctest.html) runs Python code in docstrings. Good for ensuring that the documentation is up-to-date and that examples actually works.

It seems to only work for Python shell doc strings (starting with `>>>`). Perhaps this one will be better: https://github.com/tmarktaylor/phmdoctest ?

2022-11-23 10:33 UTC, CasperWA approved these changes

2022-11-23 10:34 UTC, CasperWA commented
Squash+merge at will.

2022-11-23 14:01 UTC, merged